name: dms
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

#----------------------- PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.18.1
  url_launcher: ^6.3.1
  logger: ^2.5.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  table_calendar: ^3.0.9
  syncfusion_flutter_pdfviewer: ^24.2.9
  lucide_icons: ^0.257.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  http_parser: ^4.0.2



  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

  # Product Specific
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/dms-document-management-system-digital-business-cloud-storage-icon-digital-data_100456-10606.jpg"
#-------------------------- ./ PACKAGES END --------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


#-------------------------- LOCAL ASSETS --------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/email_otp_images/
    - assets/images/home_screen/
    - assets/images/document_logo_images/
    - assets/images/document_images/
    - assets/logos/
    - assets/pdfs/



#-------------------------- LOCAL FONTS --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800